### ISSUE TITLE
Destination directory /home/oggei/dev/k8s-the-ansible-way/roles/data-encryption/files does not exist

### ISSUE THREAD

**Issue by aogier** [prometherion/k8s-the-ansible-way#7]
run gave me this problem, we indeed have a similar file in ./roles/data-encryption/templates/encryption-config.yaml.j2

since files and templates are indeed a very distant worlds let me know how to do what

**Comment by prometherion** [comment]
Gosh, that' my fault: I missed to commit a `.gitignore` file in order to create the folder and store that kind of files: I will fix it ASAP via PR.
